const courses={loader:{name:'Ковш оператор',category:'Хүнд машин механизм',description:'Ковшны бүтэц, ажиллагааны үндсэн ойлголт, аюулгүй ажиллагаа болон бодит техник дээрх дадлагатай танилцана.',topics:['Техникийн бүтэц ба үзлэг','Аюулгүй ажиллах суурь дүрэм','Операторын дадлага']},excavator:{name:'Экскаватор оператор',category:'Хүнд машин механизм',description:'Экскаваторын ажиллагааны үндсэн зарчим, техник ашиглах аюулгүй байдал болон операторын дадлагыг хослуулна.',topics:['Техник, удирдлагын үндэс','Аюулгүй ажиллагаа','Бодит техник дээрх дадлага']},dump:{name:'Дамп оператор',category:'Хүнд машин механизм',description:'Дампын ажиллагаа, техник ашиглах суурь мэдлэг болон аюулгүй ажиллах дадлаа хөгжүүлнэ.',topics:['Техник ашиглалтын үндэс','Аюулгүй ажиллагааны дадал','Операторын дадлага']},safety:{name:'Аюулгүй ажиллагаа',category:'Сургалтын суурь',description:'Техник дээр ажиллахын өмнө эрсдэлийг таних, хамгаалах хэрэгслээ зөв хэрэглэх, аюулгүй дадлыг хэвшүүлэхэд анхаарна.',topics:['Ажлын өмнөх үзлэг','Хамгаалах хэрэгслийн хэрэглээ','Аюулгүй ажиллах хандлага']},manicure:{name:'Маникюр',category:'Гоо сайхан',description:'Хумсны арчилгаа, хэлбэр гаргалт, дизайн болон нарийн ажиллагааны ур чадварыг дадлагаар хөгжүүлнэ.',topics:['Арчилгааны үндэс','Хэлбэр, дизайн','Мэргэжлийн дадлага']},lashes:{name:'Сормуус',category:'Гоо сайхан',description:'Сормуусны нарийн ажиллагаа, техник болон үйлчлүүлэгчтэй ажиллах суурь дадлыг хөгжүүлнэ.',topics:['Техникийн үндэс','Нарийвчлал ба зөв дадал','Мэргэжлийн дадлага']}};
const detail=document.querySelector('#detail-dialog');
function showDetail(html){document.querySelector('#detail-content').innerHTML=html;detail.showModal()}
function showCourse(key){const c=courses[key];if(!c)return;showDetail(`<small>${c.category}</small><h2>${c.name}</h2><p>${c.description}</p><ul>${c.topics.map(t=>`<li>${t}</li>`).join('')}</ul><p>Элсэлтийн огноо, төлбөр, үргэлжлэх хугацааг сургалтын төвөөс баталгаажуулна.</p><button class="button primary" data-account>Бүртгэлийн мэдээлэл</button>`)}
function accountInfo(){if(window.RISE_CONFIG.accountUrl){location.href=window.RISE_CONFIG.accountUrl;return}showDetail('<h2>Суралцах дараагийн алхам</h2><p>Эхлээд хэрэглэгчийн бүртгэл үүсгэнэ. Дараа нь сургалтаа сонгож, элсэлт болон төлбөрөө баталгаажуулна.</p><p style="margin-top:20px">Онлайн бүртгэлийн үйлчилгээ хараахан холбогдоогүй байна. Шинэ ангийн огноо, төлбөрийн мэдээллийг THE RISE сургалтын төвөөс лавлана уу.</p>')}
const guides={operator:'<h2>Операторын сургалт</h2><p>THE RISE-ийн хүнд машин механизмын чиглэлд ковш, экскаватор, дампын сургалт багтана. Онолын мэдлэг, аюулгүй ажиллагаа болон бодит техник дээр дадлага хийх нь сургалтын үндсэн хэсгүүд юм.</p><p style="margin-top:20px">Өөрийн сонирхол, ажиллахыг хүсэж буй техникдээ тохируулан сургалтын чиглэлээ сонгоорой.</p>',beauty:'<h2>Beauty сургалт</h2><p>Маникюр болон сормуусны сургалт нь нарийн ажиллагаа, зөв техник, давтан дадлагад тулгуурлана. Ур чадвараа хөгжүүлэхэд тэвчээр, цэвэр ажиллагаа болон тогтмол дадлага чухал.</p>',faq:'<h2>Түгээмэл асуулт</h2><h3>Ямар сургалтууд байдаг вэ?</h3><p>Ковш, экскаватор, дамп оператор, маникюр, сормуусны сургалт.</p><h3 style="margin-top:24px">Төгсөлтийн баримт бичиг олгох уу?</h3><p>Төгссөн суралцагчид сертификат болон үнэмлэх олгоно.</p><h3 style="margin-top:24px">Хэзээ, ямар төлбөртэй эхлэх вэ?</h3><p>Анги бүрийн огноо, хугацаа, төлбөрийг THE RISE сургалтын төвөөс баталгаажуулна.</p>'};
document.addEventListener('click',e=>{const c=e.target.closest('[data-course]');if(c)showCourse(c.dataset.course);if(e.target.closest('[data-account]')){if(detail.open)detail.close();accountInfo()}const g=e.target.closest('[data-guide]');if(g)showDetail(guides[g.dataset.guide]);const close=e.target.closest('.dialog-close');if(close)close.closest('dialog').close()});
document.querySelectorAll('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()}}));
const toggle=document.querySelector('.menu-toggle'),menu=document.querySelector('.mobile-nav');function closeMenu(){menu.hidden=true;toggle.setAttribute('aria-expanded','false');document.body.classList.remove('no-scroll');toggle.setAttribute('aria-label','Цэс нээх')}
toggle.addEventListener('click',()=>{if(!menu.hidden){closeMenu();return}menu.hidden=false;toggle.setAttribute('aria-expanded','true');toggle.setAttribute('aria-label','Цэс хаах');document.body.classList.add('no-scroll')});menu.addEventListener('click',e=>{if(e.target.closest('a'))closeMenu()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeMenu()});
const search=document.querySelector('#search-dialog'),input=document.querySelector('#search-input');function searchResults(){const q=input.value.trim().toLowerCase();const matches=Object.entries(courses).filter(([,c])=>(c.name+' '+c.category).toLowerCase().includes(q));document.querySelector('#search-results').replaceChildren(...(matches.length?matches.map(([key,c])=>{const b=document.createElement('button');b.textContent=c.name;b.addEventListener('click',()=>{search.close();showCourse(key)});return b}):[Object.assign(document.createElement('p'),{textContent:'Тохирох сургалт олдсонгүй.'})]))}document.querySelector('#search-open').addEventListener('click',()=>{search.showModal();input.value='';searchResults();input.focus()});input.addEventListener('input',searchResults);
document.querySelectorAll('a[href="staff.html"]').forEach(a=>{if(window.RISE_CONFIG.staffLoginUrl)a.href=window.RISE_CONFIG.staffLoginUrl});
const sections=[...document.querySelectorAll('.showcase')],back=document.querySelector('.back-top');const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;let ticking=false;function updateScroll(){const height=innerHeight;back.classList.toggle('visible',scrollY>height*.7);if(!reduced)sections.forEach(s=>{const r=s.getBoundingClientRect(),distance=Math.abs((r.top+r.height/2)-height/2),progress=Math.max(0,1-distance/(height*.7)),card=s.firstElementChild;card.style.transform=`scale(${.7+progress*.3})`;card.style.opacity=.55+progress*.45});ticking=false}addEventListener('scroll',()=>{if(!ticking){requestAnimationFrame(updateScroll);ticking=true}},{passive:true});addEventListener('resize',()=>{if(innerWidth>767)closeMenu();updateScroll()});updateScroll();
const courseNav=document.querySelector('#course-nav'),mega=document.querySelector('#course-menu'),header=document.querySelector('.header');function setMega(open){mega.hidden=!open;courseNav.setAttribute('aria-expanded',String(open))}courseNav.addEventListener('pointerenter',()=>{if(innerWidth>767)setMega(true)});courseNav.addEventListener('click',()=>setMega(true));header.addEventListener('pointerleave',()=>setMega(false));header.addEventListener('focusout',e=>{if(!header.contains(e.relatedTarget))setMega(false)});mega.addEventListener('click',e=>{if(e.target.closest('a,button'))setMega(false)});document.addEventListener('keydown',e=>{if(e.key==='Escape')setMega(false)});let lastY=scrollY;addEventListener('scroll',()=>{header.classList.toggle('scrolling-down',scrollY>90&&scrollY>lastY);if(scrollY>lastY)setMega(false);lastY=scrollY},{passive:true});

