const iconSvg=(content)=>`<svg viewBox="0 0 24 24" aria-hidden="true">${content}</svg>`;
document.querySelectorAll('.task-actions .more').forEach(b=>b.innerHTML=iconSvg('<circle cx="5" cy="12" r="1.6"/><circle cx="12" cy="12" r="1.6"/><circle cx="19" cy="12" r="1.6"/>'));
document.querySelectorAll('.task-actions .cancel,.dialog-close').forEach(b=>b.innerHTML=iconSvg('<path d="m7 7 10 10M17 7 7 17"/>'));
document.querySelectorAll('.task-actions .done').forEach(b=>b.innerHTML=iconSvg('<path d="m5 12 4.5 4.5L19 7"/>'));
document.querySelectorAll('.check-symbol').forEach(b=>b.innerHTML=iconSvg('<circle cx="11" cy="13" r="8"/><path d="m7 12 4 4L21 5"/>'));
document.querySelectorAll('.goal-edit').forEach(b=>b.innerHTML=iconSvg('<path d="m5 16-1 4 4-1L20 7l-3-3L5 16ZM14 7l3 3"/>'));
const themes=['light','dark','night'];const themeLabels={light:'Гэгээн',dark:'Dark',night:'Night'};let theme;try{theme=localStorage.getItem('rise-theme')}catch{}if(!themes.includes(theme))theme='dark';
const themeControl=document.createElement('div');themeControl.className='theme-switch';themeControl.setAttribute('aria-label','Өнгөний горим');themeControl.innerHTML=themes.map(t=>`<button data-theme-option="${t}" aria-label="${themeLabels[t]} горим" title="${themeLabels[t]}">${iconSvg(t==='light'?'<circle cx="12" cy="12" r="4"/><path d="M12 2v2M12 20v2M2 12h2M20 12h2M5 5l1 1M18 18l1 1M19 5l-1 1M6 18l-1 1"/>':t==='dark'?'<path d="M20 14A9 9 0 0 1 10 3a9 9 0 1 0 10 11Z"/>':'<path d="M3 17a9 9 0 0 0 18 0M7 9l1-3 1 3 3 1-3 1-1 3-1-3-3-1 3-1ZM17 3v4M15 5h4"/>')}</button>`).join('');document.querySelector('.profile-wrap').before(themeControl);
function applyTheme(){document.documentElement.dataset.theme=theme;themeControl.querySelectorAll('button').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.themeOption===theme)))}applyTheme();themeControl.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;theme=b.dataset.themeOption;applyTheme();try{localStorage.setItem('rise-theme',theme)}catch{}});
