const iconSvg=(content)=>`<svg viewBox="0 0 24 24" aria-hidden="true">${content}</svg>`;
document.querySelectorAll('.task-actions .more').forEach(b=>b.innerHTML=iconSvg('<circle cx="5" cy="12" r="1.6"/><circle cx="12" cy="12" r="1.6"/><circle cx="19" cy="12" r="1.6"/>'));
document.querySelectorAll('.task-actions .cancel,.dialog-close').forEach(b=>b.innerHTML=iconSvg('<path d="m7 7 10 10M17 7 7 17"/>'));
document.querySelectorAll('.task-actions .done').forEach(b=>b.innerHTML=iconSvg('<path d="m5 12 4.5 4.5L19 7"/>'));
document.querySelectorAll('.check-symbol').forEach(b=>b.innerHTML=iconSvg('<circle cx="11" cy="13" r="8"/><path d="m7 12 4 4L21 5"/>'));
document.querySelectorAll('.goal-edit').forEach(b=>b.innerHTML=iconSvg('<path d="m5 16-1 4 4-1L20 7l-3-3L5 16ZM14 7l3 3"/>'));
const themes=['light','dark'];const themeLabels={light:'Гэгээн',dark:'Dark',night:'Night'};let theme;try{theme=localStorage.getItem('rise-theme')}catch{}if(!themes.includes(theme))theme='dark';
const themeControl=document.createElement('div');themeControl.className='theme-switch';themeControl.setAttribute('aria-label','Өнгөний горим');themeControl.innerHTML=themes.map(t=>`<button data-theme-option="${t}" aria-label="${themeLabels[t]} горим" title="${themeLabels[t]}">${iconSvg(t==='light'?'<circle cx="12" cy="12" r="4"/><path d="M12 2v2M12 20v2M2 12h2M20 12h2M5 5l1 1M18 18l1 1M19 5l-1 1M6 18l-1 1"/>':t==='dark'?'<path d="M20 14A9 9 0 0 1 10 3a9 9 0 1 0 10 11Z"/>':'<path d="M3 17a9 9 0 0 0 18 0M7 9l1-3 1 3 3 1-3 1-1 3-1-3-3-1 3-1ZM17 3v4M15 5h4"/>')}</button>`).join('');document.querySelector('.profile-wrap').before(themeControl);
function applyTheme(){document.documentElement.dataset.theme=theme;themeControl.querySelectorAll('button').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.themeOption===theme)))}applyTheme();themeControl.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;theme=b.dataset.themeOption;applyTheme();try{localStorage.setItem('rise-theme',theme)}catch{}});
// One continuous panel outline, with the tabs cut directly into its top edge.
const insetPanel=document.querySelector('.student-panel'),insetTabs=document.querySelector('.student-tabs');
function drawInset(){const w=insetPanel.clientWidth,h=insetPanel.clientHeight,tw=insetTabs.offsetWidth,th=insetTabs.offsetHeight;const l=(w-tw)/2,r=l+tw,c=Math.min(22,l-2),b=Math.min(36,th*.55),o=30;insetPanel.style.setProperty('--notch-height',th+'px');insetPanel.style.setProperty('--toolbar-left-space',Math.max(90,l-22)+'px');insetPanel.style.setProperty('--toolbar-right-space',Math.max(90,w-r-22)+'px');const fill=document.documentElement.dataset.theme==='light'?'#303030':'url(#studentCanvas)';const d=`M ${o} 0 H ${l-c} Q ${l} 0 ${l} ${c} V ${th-b} Q ${l} ${th} ${l+b} ${th} H ${r-b} Q ${r} ${th} ${r} ${th-b} V ${c} Q ${r} 0 ${r+c} 0 H ${w-o} Q ${w} 0 ${w} ${o} V ${h-o} Q ${w} ${h} ${w-o} ${h} H ${o} Q 0 ${h} 0 ${h-o} V ${o} Q 0 0 ${o} 0 Z`;const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}" viewBox="0 0 ${w} ${h}"><defs><linearGradient id="studentCanvas" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#dce9fc"/><stop offset="1" stop-color="#f8fbff"/></linearGradient></defs><path fill="${fill}" d="${d}"/></svg>`;insetPanel.style.setProperty('--inset-shape',`url("data:image/svg+xml,${encodeURIComponent(svg)}")`)}
new ResizeObserver(drawInset).observe(insetPanel);new ResizeObserver(drawInset).observe(insetTabs);new MutationObserver(drawInset).observe(document.documentElement,{attributes:true,attributeFilter:['data-theme']});drawInset();

const rosterSearch=document.querySelector('.student-search'),rosterList=document.querySelector('#student-list');function alignRosterSearch(){const row=rosterList.querySelector('.student-item');const panelRect=insetPanel.getBoundingClientRect(),rowRect=(row||rosterList).getBoundingClientRect();insetPanel.style.setProperty('--roster-search-width',rowRect.width+'px');insetPanel.style.setProperty('--roster-search-left',(rowRect.left-panelRect.left)+'px')}new ResizeObserver(alignRosterSearch).observe(rosterList);new MutationObserver(alignRosterSearch).observe(rosterList,{childList:true});alignRosterSearch();

function alignRosterTop(){const main=document.querySelector('.main-column'),profile=document.querySelector('#profile-toggle');main.style.setProperty('--roster-lift',Math.max(0,main.getBoundingClientRect().top+parseFloat(getComputedStyle(main).paddingTop)-profile.getBoundingClientRect().top)+'px')}new ResizeObserver(alignRosterTop).observe(document.querySelector('.os-header'));window.addEventListener('resize',alignRosterTop);alignRosterTop();
