// iOS-inspired single-selection menus; native selects remain as the data model.
for(const select of document.querySelectorAll('.student-filters select')){
 const trigger=document.createElement('button');trigger.type='button';trigger.className='filter-trigger';trigger.setAttribute('aria-haspopup','menu');trigger.setAttribute('aria-expanded','false');trigger.setAttribute('aria-label',select.getAttribute('aria-label'));select.hidden=true;select.after(trigger);
 const menu=document.createElement('div');menu.className='ios-filter-menu';menu.setAttribute('role','menu');menu.hidden=true;document.body.append(menu);trigger.setAttribute('aria-controls',menu.id=select.id+'-menu');
 const close=()=>{menu.hidden=true;trigger.setAttribute('aria-expanded','false')};
 const sync=()=>{trigger.textContent=select.selectedOptions[0].textContent;menu.replaceChildren(...[...select.options].map(option=>{const item=document.createElement('button');item.type='button';item.setAttribute('role','menuitemradio');item.setAttribute('aria-checked',String(option.selected));item.textContent=option.textContent;item.addEventListener('click',()=>{select.value=option.value;select.dispatchEvent(new Event('change',{bubbles:true}));sync();close();trigger.focus()});return item}))};sync();select.addEventListener('change',sync);
 const position=()=>{const r=trigger.getBoundingClientRect(),width=Math.min(244,innerWidth-24);menu.style.width=width+'px';menu.style.left=Math.max(12,Math.min(r.right-width,innerWidth-width-12))+'px';menu.style.top=Math.min(r.bottom+8,innerHeight-menu.offsetHeight-12)+'px'};
 trigger.addEventListener('click',()=>{const open=menu.hidden;document.querySelectorAll('.ios-filter-menu').forEach(m=>m.hidden=true);document.querySelectorAll('.filter-trigger').forEach(t=>t.setAttribute('aria-expanded','false'));menu.hidden=!open;trigger.setAttribute('aria-expanded',String(open));if(open){position();menu.querySelector('[aria-checked=true]')?.focus()}});
 menu.addEventListener('keydown',e=>{const items=[...menu.querySelectorAll('button')],i=items.indexOf(document.activeElement);if(e.key==='Escape'){close();trigger.focus()}else if(['ArrowDown','ArrowUp','Home','End'].includes(e.key)){e.preventDefault();items[e.key==='Home'?0:e.key==='End'?items.length-1:(i+(e.key==='ArrowDown'?1:-1)+items.length)%items.length].focus()}});document.addEventListener('click',e=>{if(!menu.contains(e.target)&&!trigger.contains(e.target))close()});window.addEventListener('resize',close);window.addEventListener('scroll',close,true);
}
